/**:
  ros__parameters:
    port: "/dev/ttyUSB0"
    baudrate: 57600
    joint_ids: [11, 12, 13, 14, 15, 2]
    joint_names:
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "wrist_rotate"
    home_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]